/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.leandro.flow;
import java.util.concurrent.SubmissionPublisher;
import java.util.stream.Stream;

import com.google.common.flogger.FluentLogger;

public class App {
    private static final FluentLogger logger = FluentLogger.forEnclosingClass();
	public static void main(String[] args) throws InterruptedException {
		logger.atInfo().log("Init");
		try (final var publisher = new SubmissionPublisher<String>()) {
			Stream.of("Cellphone", "Twitter", "Email").parallel().map(MessageSubscriber::new).forEach(publisher::subscribe);
			publisher.submit("Flow observer test");
			
			try {
	            Thread.sleep(1_000);
	        } catch (InterruptedException exception) {
	            logger.atSevere().log("Error ", exception);
	            throw exception;
	        }
		}
	}
}
