/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter2;

import chapter2.factorymethod.Employee;

public class App {
    public static void main(String[] args) {
        final Employee employeeWithSalary = Employee.createEmployeeWithSalary(1L, "John", 2000.00f);
        final Employee employeeHourlyPayed = Employee.createEmplyeeWithHourRate(2L, "Mark", 20.00f);

        System.out.println(employeeWithSalary);
        System.out.println(employeeHourlyPayed);

    }
}
